services:
  app:
    build:
      context: .
      args:
        HTTP_PROXY: ${HTTP_PROXY}
        HTTPS_PROXY: ${HTTPS_PROXY}
    container_name: reid-server-web-app
    networks:
      - reid-server_web_app_network
    env_file:
      - .env

networks:
  reid-server_web_app_network:
    external: true
